name: Python Lint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: ricardochaves/python-lint@master
        with:
          python-root-list: "tests"
          use-pylint: false
